<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'program/partial/call-selector' => __DIR__ . '//view/program/partial/call-selector.twig',
    'program/partial/form/project'  => __DIR__ . '//view/program/partial/form/project.twig',
    'program/partial/list/funder'   => __DIR__ . '//view/program/partial/list/funder.twig',
    'program/partial/list/program'  => __DIR__ . '//view/program/partial/list/program.twig',
    'program/program/view-nda-call' => __DIR__ . '//view/program/program/view-nda-call.twig',
);
