<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'program/doa/replace'                     => __DIR__ . '//view/program/doa/replace.twig',
    'program/doa/view'                        => __DIR__ . '//view/program/doa/view.twig',
    'program/doa/upload'                      => __DIR__ . '//view/program/doa/upload.twig',
    'program/pdf/nda-call'                    => __DIR__ . '//view/program/pdf/nda-call.twig',
    'program/pdf/doa-program'                 => __DIR__ . '//view/program/pdf/doa-program.twig',
    'program/pdf/nda-general'                 => __DIR__ . '//view/program/pdf/nda-general.twig',
    'program/nda/replace'                     => __DIR__ . '//view/program/nda/replace.twig',
    'program/nda/view'                        => __DIR__ . '//view/program/nda/view.twig',
    'program/nda/upload'                      => __DIR__ . '//view/program/nda/upload.twig',
    'program/partial/list/program'            => __DIR__ . '//view/program/partial/list/program.twig',
    'program/partial/list/funder'             => __DIR__ . '//view/program/partial/list/funder.twig',
    'program/partial/form/project'            => __DIR__ . '//view/program/partial/form/project.twig',
    'program/partial/entity/programcall-info' => __DIR__ . '//view/program/partial/entity/programcall-info.twig',
    'program/partial/entity/session'          => __DIR__ . '//view/program/partial/entity/session.twig',
    'program/partial/call-selector'           => __DIR__ . '//view/program/partial/call-selector.twig',
);
