<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'program/nda/view-call'         => __DIR__ . '//view/program/nda/view-call.twig',
    'program/nda/view'              => __DIR__ . '//view/program/nda/view.twig',
    'program/partial/call-selector' => __DIR__ . '//view/program/partial/call-selector.twig',
    'program/partial/form/project'  => __DIR__ . '//view/program/partial/form/project.twig',
    'program/partial/list/funder'   => __DIR__ . '//view/program/partial/list/funder.twig',
    'program/partial/list/program'  => __DIR__ . '//view/program/partial/list/program.twig',
    'program/pdf/nda-call'          => __DIR__ . '//view/program/pdf/nda-call.twig',
    'program/pdf/nda-general'       => __DIR__ . '//view/program/pdf/nda-general.twig',
);
