<?php
_("txt-no-doa-required");
_("txt-doa-per-program-required");
_("txt-doa-per-project-required");
_("txt-po-open-date");
_("txt-po-close-date");
_("txt-po-grace-date");
_("txt-fpp-open-date");
_("txt-fpp-close-date");
_("txt-fpp-grace-date");
_("txt-doa-requirements");
_("txt-po-grace-date-inline-help");
_("txt-fpp-grace-date-inline-help");
_("txt-doa-requirements-inline-help");
_("txt-partners");